apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mssqlserver
  template:
    metadata:
      labels:
        name: mssqlserver
    spec:
      volumes:
        - name: sqlserver-persistent-storage
          persistentVolumeClaim:
            claimName: sqlserverpvclaim
      containers:
        - name: mssql-cont
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sqlserver-persistent-storage
              mountPath: /var/opt/sql
              subPath: mssqlserver
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: sql@123U