apiVersion: apps/v1
kind: Deployment
metadata:
  name:  dockersqlserver
  namespace: default
  labels:
    app:  dockersqlserver
spec:
  selector:
    matchLabels:
      app: dockersqlserver
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  dockersqlserver
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  dockersqlserver
        image:  edangol/dockersqlserver
        resources:
          requests:
            cpu: 512m
            memory: 512Mi
          limits:
            cpu: 512m
            memory: 512Mi
        
        env:
          - name: ConnectionStrings__SqlConnection
            value: "Server=dockersqlserverdb-service,1433;Database=products;User Id=SA;Password=sql@123U;"
          - name: SA_PASSWORD
            value: sql@123U
        ports:
        - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: dockersqlserver-service
  namespace: default
spec:
  selector:
    app: dockersqlserver
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer

        