apiVersion: apps/v1
kind: Deployment
metadata:
  name:  evanginx-deployment
  namespace: default
  labels:
    app:  evanginx
spec:
  selector:
    matchLabels:
      app: evanginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  evanginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  evanginx
        image:  edangol/evanginx
       