apiVersion: v1
kind: Service
metadata:
  name: evanginx-service
  namespace: default
spec:
  selector:
    app: evanginx
  type: LoadBalancer
  
  ports:
  - name: evanginx
    protocol: TCP
    port: 80
    targetPort: 80
  